# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}  
      - name: Install dependencies
        run: dotnet restore 
      - name: Build solution and generate NuGet package
        run: |  
          cd OAuth.Erogames
          dotnet pack -c Release -o out  
      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./OAuth.Erogames/out/*.nupkg --skip-duplicate --no-symbols true --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}} 
